/node_modules
/vendor
/.git
/.env
/.idea
/.vscode
/storage/*.sqlite
/storage/logs/*
/storage/framework/cache/*
/storage/framework/sessions/*
/storage/framework/views/*
!/storage/framework/cache/.gitignore
!/storage/framework/sessions/.gitignore
!/storage/framework/views/.gitignore
!/storage/logs/.gitignore
/public/build
/public/hot
/public/storage
.env.example
.gitignore
docker-compose.yml
README.md